package org.cantact.ui;

import org.cantact.core.CanFrame;
import org.cantact.core.DeviceManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//org.cantact.ui//Transmit//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "TransmitTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = true)
@ActionID(category = "Window", id = "org.cantact.ui.TransmitTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_TransmitAction",
        preferredID = "TransmitTopComponent"
)
@Messages({
    "CTL_TransmitAction=Transmit",
    "CTL_TransmitTopComponent=Transmit Window",
    "HINT_TransmitTopComponent=This is a Transmit window"
})
public final class TransmitTopComponent extends TopComponent {
    public TransmitTopComponent() {
        initComponents();
        setName(Bundle.CTL_TransmitTopComponent());
        setToolTipText(Bundle.HINT_TransmitTopComponent());
        putClientProperty(TopComponent.PROP_MAXIMIZATION_DISABLED, Boolean.TRUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        byte0Field = new javax.swing.JTextField();
        byte1Field = new javax.swing.JTextField();
        byte2Field = new javax.swing.JTextField();
        byte3Field = new javax.swing.JTextField();
        byte4Field = new javax.swing.JTextField();
        byte5Field = new javax.swing.JTextField();
        byte6Field = new javax.swing.JTextField();
        byte7Field = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dlcComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        transmitButton = new javax.swing.JButton();

        byte0Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte0Field.text")); // NOI18N
        add(byte0Field);
        byte0Field.setBounds(60, 280, 38, 20);

        byte1Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte1Field.text")); // NOI18N
        add(byte1Field);
        byte1Field.setBounds(110, 280, 38, 20);

        byte2Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte2Field.text")); // NOI18N
        add(byte2Field);
        byte2Field.setBounds(160, 280, 38, 20);

        byte3Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte3Field.text")); // NOI18N
        add(byte3Field);
        byte3Field.setBounds(210, 280, 38, 20);

        byte4Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte4Field.text")); // NOI18N
        add(byte4Field);
        byte4Field.setBounds(260, 280, 38, 20);

        byte5Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte5Field.text")); // NOI18N
        add(byte5Field);
        byte5Field.setBounds(310, 280, 38, 20);

        byte6Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte6Field.text")); // NOI18N
        add(byte6Field);
        byte6Field.setBounds(360, 280, 38, 20);

        byte7Field.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.byte7Field.text")); // NOI18N
        add(byte7Field);
        byte7Field.setBounds(410, 280, 38, 20);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.jLabel1.text")); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(62, 258, 23, 14);

        idField.setText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.idField.text")); // NOI18N
        idField.setToolTipText(org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.idField.toolTipText")); // NOI18N
        idField.setMinimumSize(new java.awt.Dimension(30, 20));
        idField.setPreferredSize(new java.awt.Dimension(62, 20));
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        add(idField);
        idField.setBounds(62, 186, 70, 20);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.jLabel2.text")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(62, 166, 35, 14);

        dlcComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        dlcComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlcComboBoxActionPerformed(evt);
            }
        });
        add(dlcComboBox);
        dlcComboBox.setBounds(62, 232, 31, 20);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.jLabel3.text")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(62, 212, 19, 14);

        org.openide.awt.Mnemonics.setLocalizedText(transmitButton, org.openide.util.NbBundle.getMessage(TransmitTopComponent.class, "TransmitTopComponent.transmitButton.text")); // NOI18N
        transmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmitButtonActionPerformed(evt);
            }
        });
        add(transmitButton);
        transmitButton.setBounds(60, 310, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void transmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmitButtonActionPerformed
        CanFrame txFrame = new CanFrame();
        txFrame.setId(Integer.decode(idField.getText()));
        txFrame.setDlc(Integer.decode(dlcComboBox.getSelectedItem().toString()));
        int[] data = {
            Integer.decode(byte0Field.getText()),
            Integer.decode(byte1Field.getText()),
            Integer.decode(byte2Field.getText()),
            Integer.decode(byte3Field.getText()),
            Integer.decode(byte4Field.getText()),
            Integer.decode(byte5Field.getText()),
            Integer.decode(byte6Field.getText()),
            Integer.decode(byte7Field.getText())
        };
        txFrame.setData(data);
        DeviceManager.transmit(txFrame);
    }//GEN-LAST:event_transmitButtonActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void dlcComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlcComboBoxActionPerformed

    switch(Integer.decode(dlcComboBox.getSelectedItem().toString())){
        case 1:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(false);
            this.byte2Field.setVisible(false);
            this.byte3Field.setVisible(false);
            this.byte4Field.setVisible(false);
            this.byte5Field.setVisible(false);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
        case 2:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(false);
            this.byte3Field.setVisible(false);
            this.byte4Field.setVisible(false);
            this.byte5Field.setVisible(false);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
        case 3:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(true);
            this.byte3Field.setVisible(false);
            this.byte4Field.setVisible(false);
            this.byte5Field.setVisible(false);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
        case 4:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(true);
            this.byte3Field.setVisible(true);
            this.byte4Field.setVisible(false);
            this.byte5Field.setVisible(false);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
        case 5:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(true);
            this.byte3Field.setVisible(true);
            this.byte4Field.setVisible(true);
            this.byte5Field.setVisible(false);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
        case 6:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(true);
            this.byte3Field.setVisible(true);
            this.byte4Field.setVisible(true);
            this.byte5Field.setVisible(true);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
        case 7:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(true);
            this.byte3Field.setVisible(true);
            this.byte4Field.setVisible(true);
            this.byte5Field.setVisible(true);
            this.byte6Field.setVisible(true);
            this.byte7Field.setVisible(false);
            break;
        case 8:
            this.byte0Field.setVisible(true);
            this.byte1Field.setVisible(true);
            this.byte2Field.setVisible(true);
            this.byte3Field.setVisible(true);
            this.byte4Field.setVisible(true);
            this.byte5Field.setVisible(true);
            this.byte6Field.setVisible(true);
            this.byte7Field.setVisible(true);
            break;
        default:
            this.byte0Field.setVisible(false);
            this.byte1Field.setVisible(false);
            this.byte2Field.setVisible(false);
            this.byte3Field.setVisible(false);
            this.byte4Field.setVisible(false);
            this.byte5Field.setVisible(false);
            this.byte6Field.setVisible(false);
            this.byte7Field.setVisible(false);
            break;
    }
    }//GEN-LAST:event_dlcComboBoxActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField byte0Field;
    private javax.swing.JTextField byte1Field;
    private javax.swing.JTextField byte2Field;
    private javax.swing.JTextField byte3Field;
    private javax.swing.JTextField byte4Field;
    private javax.swing.JTextField byte5Field;
    private javax.swing.JTextField byte6Field;
    private javax.swing.JTextField byte7Field;
    private javax.swing.JComboBox dlcComboBox;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton transmitButton;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}